version: '3'
services:
    web-application:
        build: web-application
        ports:
            - "8080:8080"
            - "9229:9229"
        volumes:
            - "./web-application/src:/my-web-app/src"
        depends_on:
            - database
    database:
        build: ./database
        ports:
            - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=hemligt
            - MYSQL_DATABASE=webAppDatabase
    session-database:
        build: session-database
        ports:
            - "6379:6379"